language: php

sudo: false

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0
  fast_finish: true

sudo: false

install: travis_retry composer install --no-interaction --prefer-source

script: vendor/bin/phpspec run -v
